const data = {
  products: [
    {
      _id: "1",
      name: "T500 Plus Smart Watch",
      category: "Watches",
      image: "/images/1.jpeg",
      price: 60,
      countInStock: 10,
      brand: "T500",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "2",
      name: "Mega Safe Charger",
      category: "Charger",
      image: "/images/2.png",
      price: 30,
      countInStock: 0,
      rating: 4,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "3",
      name: "Smart Watch for Kids",
      category: "Watches",
      image: "/images/3.jpeg",
      price: 60,
      countInStock: 15,
      rating: 5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "4",
      name: "Power Adapter USB C",
      category: "Adapter",
      image: "/images/4.jpeg",
      price: 20,
      countInStock: 20,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "5",
      name: "Smart Bulb",
      category: "Bulb",
      image: "/images/5.jpeg",
      price: 15,
      countInStock: 12,
      rating: 5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "6",
      name: "Smart Adapter",
      category: "Adapter",
      image: "/images/6.jpeg",
      price: 20,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "7",
      name: "Air Pods",
      category: "Air Pod",
      image: "/images/7.jpeg",
      price: 60,
      countInStock: 16,
      rating: 5,
      numReviews: 10,
      description: "high quality products",
    },
  ],
};
export default data;
